CREATE TABLE public.users (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username       TEXT    NOT NULL UNIQUE,
  email          TEXT    NOT NULL UNIQUE,
  password_hash  TEXT    NOT NULL,
  score          INTEGER NOT NULL DEFAULT 0 CHECK (score >= 0),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_login_at  TIMESTAMPTZ
);
